---
apiVersion: v1
kind: Service
metadata:
  annotations:
    fabric8.io/scm-url: https://github.com/spring-projects/spring-boot/spring-boot-starter-parent/activity-service
    fabric8.io/scm-tag: HEAD
    prometheus.io/port: "9779"
    prometheus.io/scrape: "true"
  labels:
    app: activity-service
    provider: fabric8
    version: 1.0.0
    group: com.fis.hotel
  name: activity-service
spec:
  ports:
  - port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    app: activity-service
    provider: fabric8
    group: com.fis.hotel
  type: NodePort
