---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    fabric8.io/scm-url: https://github.com/spring-projects/spring-boot/spring-boot-starter-parent/activity-service
    fabric8.io/scm-tag: HEAD
  labels:
    app: activity-service
    provider: fabric8
    version: 1.0.0
    group: com.fis.hotel
  name: activity-service
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    app: activity-service
    provider: fabric8
    group: com.fis.hotel
  strategy:
    rollingParams:
      timeoutSeconds: 3600
    type: Rolling
  template:
    metadata:
      annotations:
        fabric8.io/scm-tag: HEAD
        fabric8.io/scm-url: https://github.com/spring-projects/spring-boot/spring-boot-starter-parent/activity-service
      labels:
        app: activity-service
        provider: fabric8
        version: 1.0.0
        group: com.fis.hotel
    spec:
      containers:
      - env:
        - name: TZ
          value: Asia/Ho_Chi_Minh
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: hotel/activity-service:1.0.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 180
          successThreshold: 1
          tcpSocket:
            port: 8090
        name: spring-boot
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8090
        securityContext:
          privileged: false
  triggers:
  - type: ConfigChange
